//! smir::lift::x86_64::scalar submodules

mod arithmetic;
pub use arithmetic::*;
mod control_flow;
pub use control_flow::*;
mod control_regs;
pub use control_regs::*;
mod crc32;
pub use crc32::*;
mod debug_regs;
pub use debug_regs::*;
mod data_movement;
pub use data_movement::*;
mod movdir;
pub use movdir::*;
mod group11;
pub use group11::*;
mod group15;
pub use group15::*;
mod group5;
pub use group5::*;
mod machine_status;
pub use machine_status::*;
mod selector;
pub use selector::*;
mod shift_bit;
pub use shift_bit::*;
mod string;
pub use string::*;
mod system;
pub use system::*;
mod tsx;
pub use tsx::*;
mod x87;
pub use x87::*;
