//! Architectural trap terminators.

use crate::smir::ir::types::GuestAddr;

/// Trap kinds represented as terminal SMIR control flow.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum TrapKind {
    /// Debug breakpoint.
    Breakpoint,
    /// x86 trap-class debug exception generated by `INT1`/`ICEBP` (`F1`).
    ///
    /// `fault_pc` identifies the instruction for an APX-disabled REX2 encoding;
    /// `return_pc` is the post-instruction RIP saved by a successful #DB.
    X86Debug {
        fault_pc: GuestAddr,
        return_pc: GuestAddr,
        requires_apx: bool,
    },
    /// x86 software interrupt generated by `INT imm8` (`CD ib`).
    ///
    /// `fault_pc` identifies the instruction for an APX-disabled REX2 encoding;
    /// `return_pc` is the post-instruction RIP saved after successful gate
    /// delivery. Gate lookup, DPL validation, and architectural frame creation
    /// remain an interpreter/runtime boundary.
    X86SoftwareInterrupt {
        vector: u8,
        fault_pc: GuestAddr,
        return_pc: GuestAddr,
        requires_apx: bool,
    },
    /// Undefined instruction.
    Undefined,
    /// Division by zero.
    DivideByZero,
    /// Integer overflow.
    Overflow,
    /// Bounds-check failure.
    Bounds,
    /// Invalid opcode.
    InvalidOpcode,
    /// System call.
    SystemCall,
    /// Halt and wait for interrupt.
    Halt,
    /// x86 general-protection exception with architectural error code zero.
    GeneralProtection,
}
